version: "3.8"

services:
  db:
    image: postgres:16
    container_name: marble-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - marble-db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: always

  app:
    image: chjcoder/marble-app:dev-latest
    container_name: marble-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      # 필요하면 프로필 등 추가 가능
      # SPRING_PROFILES_ACTIVE: prod
    ports:
      - "${APP_PORT:-8080}:8080"
    restart: always

volumes:
  marble-db-data:
