name: Java CI with Gradle

on:
  # dev 브랜치로 들어오는 PR 검사
  pull_request:
    branches: [ "dev" ]

  # dev 브랜치에 코드가 합쳐졌을 때 (push) 배포
  push:
    branches: [ "dev" ]

jobs:
  # 1. Gradle 빌드/테스트
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

  # 2. Docker 이미지 빌드 & Docker Hub push
  docker:
    needs: build
    runs-on: ubuntu-latest

    # dev 브랜치로 push 될 때만 동작
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # EC2에서 compose로 사용하는 태그와 동일해야 함
          tags: chjcoder/marble-app:dev

  # 3. EC2 배포
  deploy:
    needs: docker
    runs-on: ubuntu-latest

    # dev 브랜치로 push 될 때만 배포
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
      - name: Deploy to EC2 via SSH (Docker Deployment)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 배포 디렉토리 이동 (docker-compose.yml 위치)
            cd /home/ubuntu/marble

            # 아래 코드 쉘 스크립트에 있음
            sh deploy.sh
            # # 최신 코드 가져오기 (docker-compose.yml 업데이트 대응)
            # git fetch origin
            # git checkout dev
            # git pull origin dev

            # # 최신 도커 이미지 pull
            # docker compose pull app

            # # 컨테이너 재시작
            # docker compose up -d --force-recreate

            # # 필요 없는 이미지 제거
            # docker image prune -f

  # 4. (선택) dependency graph
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
